/* eslint-disable @typescript-eslint/naming-convention */
export enum AppConfig {
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXP = 'JWT_EXP',
  HASH_ROUNDS = 'HASH_ROUNDS',
  POSTGRES_HOST = 'POSTGRES_HOST',
  POSTGRES_PORT = 'POSTGRES_PORT',
  POSTGRES_USER = 'POSTGRES_USER',
  POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
  POSTGRES_DB = 'POSTGRES_DB',
  RATE_LIMITER_TTL = 'RATE_LIMITER_TTL',
  RATE_LIMITER_LIMIT = 'RATE_LIMITER_LIMIT',
}
